[Issue-63]: Add Thread class
Rreyth/get-transcended pull request #71
Opened 2024-05-15 09:04 UTC by ltuffery

2024-05-15 10:40 UTC, Rreyth requested changes
docs/Thread.md 
pas de texte en français chacal

2024-05-16 06:22 UTC, ltuffery commented
> docs/Thread.md pas de texte en français chacal

Toute les autres doc sont en francais, cela ne serais pas coherant de n'avoir qu'un seul fichier en FR

2024-05-18 06:01 UTC, Rreyth requested changes
pourquoi changer le port du jeu ? (pong.js - 62)

2024-05-18 06:01 UTC, Rreyth commented on srcs/django_code/front/js/pong.js
> +	const socket = "wss://" + window.location.hostname + ":8760";
?????????????????????????????????????????????????????????

2024-05-18 08:41 UTC, ltuffery commented on srcs/django_code/front/js/pong.js
> +	const socket = "wss://" + window.location.hostname + ":8760";
Erreur de ma part, je voulais tester que le thread etais bien clean, donc j'ai mis un port qui n'existe pas pour activer le setTimeout d'erreur du jeu, j'ai juste oublier de remettre le bon port

2024-05-18 08:44 UTC, ltuffery commented on srcs/django_code/front/js/pong.js
> +	const socket = "wss://" + window.location.hostname + ":8760";
Fix ici [be8aed6](https://github.com/Rreyth/get-transcended/pull/71/commits/be8aed62ab50d8da93f322ffbe23524f10875e6e)

2024-05-18 09:03 UTC, Rreyth approved these changes
![knuckles](https://github.com/Rreyth/get-transcended/assets/109280660/87d26743-6ccd-4b48-94e8-53e065d6b3ff)

2024-05-19 08:09 UTC, merged